### ISSUE TITLE
Acrescentar classe à frase atual

### ISSUE THREAD

**Issue by waldyrious** [colobas/debates2024#10]
A transcrição já faz scroll automaticamente em sincronização com o vídeo, o que é excelente; mas neste momento não é claro qual dos blocos da transcrição está realmente ativo, porque vários são visíveis ao mesmo tempo.

Era bom haver uma classe atribuída ao elemento da transcrição correspondente ao áudio atualmente em reprodução, para que ele pudesse ser sinalizado via CSS.

**Comment by colobas** [comment]
Parece-me estar a funcionar (Firefox em MacOS)
Se não estiver, reabre o issue sff.
