### ISSUE TITLE
Repositório extremamente pesado

### ISSUE THREAD

**Issue by waldyrious** [colobas/debates2024#6]
O repositório tem neste momento mais de 2 GB de conteúdo, praticamente todo na pasta [hls](https://github.com/colobas/debates2024/tree/main/public/debates/hls), e demora uma eternidade a clonar. Não seria melhor alojar os vídeos no YouTube ou Vimeo (ou PeerTube :smiley:) e fazer embed, em vez de armazenar como parte do repositório git?

**Comment by colobas** [comment]
Sim, tens razão. Estou a tratar disto

**Comment by colobas** [comment]
Bem o Vimeo free só aceita 3 vídeos, e o YouTube tá a bloquear os meus uploads. Alguma ideia?

**Comment by waldyrious** [comment]
Bem, supostamente tens o PeerTube. Nunca usei pessoalmente, mas pelo que estive a ver há [várias instâncias que podes usar](https://joinpeertube.org/instances?profile=video-maker&nsfw=no-opinion&quota=5000000000&isStreamer=no) — podes tentar ver p.ex. o https://veedeo.org.

Outra alternativa é o [archive.org](https://archive.org). Já o usei várias vezes para fazer arquivos de páginas web e até documentos como PDFs, mas não sei como funcionam com vídeos. Sei que [permitem carregar](https://archive.org/create/) mas dizem "Please contribute books, audio, and video files **that you have the right to share**". Não sei se são muito cautelosos nesse aspeto, mas não custa tentar :)

**Comment by colobas** [comment]
em princípio já resolvi. deve ficar live daqui a umas horas

**Comment by waldyrious** [comment]
Nice! Possivelmente será preciso fazer um [rebuild do histórico do repositório](https://stackoverflow.com/questions/2100907/how-can-i-remove-delete-a-large-file-from-the-commit-history-in-the-git-reposito), mantendo os commits mas retirando os blobs dos ficheiros pesados. Caso contrário o clone inicial (incluindo no CI, presumo) continuará a ser pesado e lento :)

**Comment by colobas** [comment]
Está live!
